FROM archlinux:base-devel

RUN curl -fsSL "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" | \
    bsdtar -C / -xvf - && \
    pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx \
    python-sphinx_rtd_theme graphviz imagemagick git python2 python zip xxd

CMD ["bash"]
